import test from 'node:test';import assert from 'node:assert/strict';import {normalizeDomain,normalizeStatuses,deriveState,inspectDomain,_resetForTests} from '../domainstate.mjs';
function mockFetch({bootstrap,domainStatus=200,domainBody={}}){return async url=>String(url).includes('data.iana.org/rdap/dns.json')?{ok:true,status:200,json:async()=>bootstrap}:{ok:domainStatus>=200&&domainStatus<300,status:domainStatus,json:async()=>domainBody}}
test('normalizes domains',()=>{assert.equal(normalizeDomain('Example.COM.'),'example.com');assert.throws(()=>normalizeDomain('https://example.com'));assert.throws(()=>normalizeDomain('x@example.com'))});
test('normalizes statuses',()=>assert.deepEqual(normalizeStatuses(['clientHold','pendingDelete']),['client hold','pending delete']));
test('state precedence',()=>{assert.equal(deriveState({status:['pendingDelete']}),'PENDING_DELETE');assert.equal(deriveState({status:['redemptionPeriod']}),'REDEMPTION');assert.equal(deriveState({status:['serverHold']}),'HOLD');assert.equal(deriveState({status:[],expiresAt:'2026-08-20T00:00:00Z',now:Date.parse('2026-08-14T00:00:00Z')}),'EXPIRING')});
test('200 domain object',async()=>{_resetForTests();const out=await inspectDomain('example.com',{now:Date.parse('2026-08-14T00:00:00Z'),fetchImpl:mockFetch({bootstrap:{services:[[['com'],['https://rdap.example/']]]},domainBody:{objectClassName:'domain',status:['clientTransferProhibited'],events:[{eventAction:'registration',eventDate:'2020-01-01T00:00:00Z'},{eventAction:'expiration',eventDate:'2030-01-01T00:00:00Z'}],nameservers:[{ldhName:'NS1.EXAMPLE.NET'}],entities:[{roles:['registrar'],vcardArray:['vcard',[['fn',{},'text','Example Registrar']]]}]}})});assert.equal(out.state,'REGISTERED');assert.equal(out.registrar,'Example Registrar');assert.equal(out.confidence,'HIGH')});
test('404 proves unregistered',async()=>{_resetForTests();const out=await inspectDomain('not-real-123.com',{fetchImpl:mockFetch({bootstrap:{services:[[['com'],['https://rdap.example/']]]},domainStatus:404})});assert.equal(out.state,'UNREGISTERED')});
test('429 stays unknown',async()=>{_resetForTests();const out=await inspectDomain('example.com',{fetchImpl:mockFetch({bootstrap:{services:[[['com'],['https://rdap.example/']]]},domainStatus:429})});assert.equal(out.state,'UNKNOWN')});
test('unsupported tld stays unknown',async()=>{_resetForTests();const out=await inspectDomain('example.invalidtld',{fetchImpl:mockFetch({bootstrap:{services:[[['com'],['https://rdap.example/']]]}})});assert.equal(out.state,'UNKNOWN')});
