import http from 'node:http';
import crypto from 'node:crypto';
import {inspectDomain} from './domainstate.mjs';
const PORT=Number(process.env.PORT||8789), BASE=process.env.PUBLIC_BASE_URL||'https://domainstate-api.onrender.com';
const internalUA=/curl|postman|validator|health|uptime|domainstate-internal|sterling-activity-dashboard|render\/health/i, coreEvents=[];
function send(res,s,o,h={}){res.writeHead(s,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','cache-control':'no-store',...h});res.end(JSON.stringify(o))}
function html(res,s,b){res.writeHead(s,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(b)}
function caller(req){const f=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return crypto.createHash('sha256').update(`${f||req.socket.remoteAddress||''}|${req.headers['user-agent']||''}`).digest('hex').slice(0,16)}
function cls(req){return req.headers['x-domainstate-test']==='1'||req.headers['x-tollbooth-internal']==='1'||internalUA.test(String(req.headers['user-agent']||''))?'KNOWN_VALIDATOR':'UNKNOWN_MACHINE'}
function record(req,event,extra={}){const e={at:new Date().toISOString(),event,caller:caller(req),classification:cls(req),method:req.method,path:req.url,...extra};coreEvents.push(e);if(coreEvents.length>1000)coreEvents.shift();console.log(JSON.stringify({service:'DOMAINSTATE',...e}))}
function activity(){const e=coreEvents.filter(x=>x.classification!=='KNOWN_VALIDATOR'),c=new Set(e.map(x=>x.caller)),v=new Set(e.filter(x=>x.classification==='CREDIBLE_REAL_USE').map(x=>x.caller));return {service:'DOMAINSTATE',generatedAt:new Date().toISOString(),realUse:{allTimeCalls:e.length,allTimeCallers:c.size,allTimeVerifiedStrangers:v.size},candidateRealUse:e.slice(-50).reverse(),verificationPolicy:{rule:'Core use is evidence of use, not automatically evidence of a genuine stranger.',classes:['KNOWN_VALIDATOR','LIKELY_VALIDATOR','UNKNOWN_MACHINE','CREDIBLE_REAL_USE']}}}
async function readJson(req){let t='';for await(const c of req){t+=c;if(t.length>10000)throw Error('body_too_large')}return JSON.parse(t||'{}')}
function docs(){return `<!doctype html><meta name="viewport" content="width=device-width"><title>DOMAINSTATE API</title><style>body{font:16px system-ui;max-width:900px;margin:50px auto;padding:20px;color:#142016}h1{font-size:54px;letter-spacing:-3px}code,pre{background:#f2f4ef;padding:3px 6px;border-radius:6px}pre{padding:16px;overflow:auto}input,button{padding:11px;font:inherit}</style><h1>DOMAINSTATE</h1><p><b>Domain → current registration state.</b></p><p>Authoritative RDAP only. UNKNOWN is a valid answer. No WHOIS history, registrant PII, or threat scoring.</p><h2>Try it</h2><form action="/play" method="get"><input name="domain" value="example.com"><button>Check domain</button></form><h2>REST</h2><pre>GET ${BASE}/v1/domain/example.com</pre><h2>MCP</h2><p>POST <code>${BASE}/mcp</code> · tool <code>inspect_domain_state</code></p><p><a href="/openapi.json">OpenAPI</a> · <a href="/sources">Sources</a> · <a href="/health">Health</a></p>`}
function openapi(){return {openapi:'3.1.0',info:{title:'DOMAINSTATE API',version:'1.0.0',description:'Normalize authoritative RDAP into a small current domain-registration state.'},servers:[{url:BASE}],paths:{'/v1/domain/{domain}':{get:{summary:'Inspect current domain registration state',parameters:[{name:'domain',in:'path',required:true,schema:{type:'string'}}],responses:{'200':{description:'Current normalized domain state'},'400':{description:'Invalid domain input'}}}}}}}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-domainstate-test,x-tollbooth-internal','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}const u=new URL(req.url,BASE);
if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:'DOMAINSTATE',version:'1.0.0'});
if(req.method==='GET'&&u.pathname==='/v1/activity')return send(res,200,activity());
if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/docs'))return html(res,200,docs());
if(req.method==='GET'&&u.pathname==='/openapi.json')return send(res,200,openapi());
if(req.method==='GET'&&u.pathname==='/sources')return send(res,200,{methodology:'IANA RDAP DNS bootstrap selects the authoritative RDAP service for the TLD. DOMAINSTATE then queries that service directly and normalizes only explicit RDAP evidence.',sources:[{name:'IANA RDAP DNS bootstrap',url:'https://data.iana.org/rdap/dns.json'},{name:'Authoritative registry/registrar RDAP',purpose:'current domain object, statuses, events, registrar, nameservers'}],state_rules:{PENDING_DELETE:'explicit pending delete status',REDEMPTION:'explicit redemption period status',HOLD:'explicit client hold or server hold status',EXPIRING:'authoritative expiration event within configured threshold (default 30 days)',REGISTERED:'authoritative RDAP returned a domain object and no higher-priority state applied',UNREGISTERED:'authoritative RDAP returned HTTP 404',UNKNOWN:'anything insufficient, ambiguous, unavailable, unsupported, rate-limited, or non-authoritative'}});
if(req.method==='GET'&&u.pathname==='/play'){const out=await inspectDomain(u.searchParams.get('domain')||'');return html(res,200,`<meta name="viewport" content="width=device-width"><style>body{font:16px system-ui;max-width:800px;margin:50px auto;padding:20px}pre{background:#f2f4ef;padding:16px;overflow:auto}</style><h1>${out.domain}</h1><pre>${JSON.stringify(out,null,2).replace(/</g,'&lt;')}</pre><p><a href="/docs">← DOMAINSTATE</a></p>`)}
if(req.method==='GET'&&u.pathname.startsWith('/v1/domain/')){const out=await inspectDomain(decodeURIComponent(u.pathname.slice('/v1/domain/'.length)));record(req,'core_lookup',{domain:out.domain,state:out.state});return send(res,200,out)}
if(req.method==='POST'&&u.pathname==='/mcp'){const j=await readJson(req);if(j.method==='initialize')return send(res,200,{jsonrpc:'2.0',id:j.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{}},serverInfo:{name:'domainstate',version:'1.0.0'}}});if(j.method==='tools/list')return send(res,200,{jsonrpc:'2.0',id:j.id,result:{tools:[{name:'inspect_domain_state',description:'Get current authoritative domain registration state from RDAP.',inputSchema:{type:'object',properties:{domain:{type:'string'}},required:['domain']}}]}});if(j.method==='tools/call'&&j.params?.name==='inspect_domain_state'){const out=await inspectDomain(j.params?.arguments?.domain);record(req,'mcp_tool_call',{domain:out.domain,state:out.state});return send(res,200,{jsonrpc:'2.0',id:j.id,result:{content:[{type:'text',text:JSON.stringify(out)}],structuredContent:out}})}return send(res,400,{jsonrpc:'2.0',id:j.id,error:{code:-32601,message:'Method not found'}})}
return send(res,404,{error:'not_found'})}catch(e){return send(res,['domain_required','domain_only_required','invalid_domain'].includes(e?.message)?400:500,{error:e?.message||'internal_error'})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`DOMAINSTATE listening on ${PORT}`));
